config/routes.rb
Tasks::Application.routes.draw do
  root :to => "Tasks#index"
 

  resources :tasks
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task
  #Don't know exactly how this works, but returns if statement necessary. See update control
  validates :task, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  #A action created by the 'rails g controller Tasks index' command line function. A veiw was also automatically generated. 
  #This action transfers specifically to the index view. Rails default. 
  def index
    #Here we use the @tasks variables so that this variable is accesible in the veiw of index as well. We pass the variables all
    #the task rows from the database
    @tasks= Task.all
    #We want to be accesible in the veiw as well as in functions below. 
    @task =Task.new
  end
  
  #When a post-request is sent to the indicated page, it will look for a create function in the controller. 
  def create
    #params is the variable given by the post/get request. In php, this is equal to _POST, _GET
    #The render generates the text in a webbrowser
    #render :text => params.inspect
      
    #Creates the model using the data passed from the form. Params represents all the data, while the hash is passed with the :task as
    #the index. 
    Task.create params[:task]
    
    #The post redirects to the /task page. Here we force the browser to go back to the main veiw page. 
    redirect_to :back
    
    
  end
  
  # Routeing after edit button clicked
  def edit
    #Tasks will be set each time we have an edit. Since form is set based on @tasks, the form will be different each time. 
    @task = Task.find params[:id]
  end
  
  # Routing after update button on form (on edit veiw) clicked
  def update
    #The :id is passed in through routing. The task is a local variable. 
    task= Task.find params[:id]
    #Here we update the attribute of the approriate Task in the table with the :task provided by the routing
    #Validation is necessary here topass a false on teh first if statement. 
    if task.update_attributes params[:task]
      redirect_to tasks_path, :notice => "Your Task has been successfully updated."
    else
      # This would be to the edit page. Update triggers that we whould move away from current page. 
      #The notice is displace on the browser
      redirect_to :back, :notice => "There was an error updating your task."
    end
    
  end
  
  #the id is passed in here
  def destroy
    Task.destroy params[:id]
    redirect_to :back, :notice => "Task has been deleted. "
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Here, we create a flash message, which is functionality provided by rails. -->
<% flash.each do |name, message|%>
<!-- Here we label the div and return them message.  -->
	<div id="flash_<%= name%>">
		<%= message %>
	</div>
<%end%>

<%= yield %>


</body>
</html>

app/views/tasks/_form.html.erb
<!-- This is a partial. We use this as re-usable front end code. -->

<!-- Here, we create a form with Ruby. The f block variable is the form that we manipulate. 
We pass in a new Task that can be accessed in the block. The form_for connects the action of the form with /tasks (tasks_path)-->
<!-- we replaced Task.new with @task which is set-up in index and essentially makes sure that a form set through edit is different. -->
<%= form_for(@task) do |f| %>
	<!--Label the form with :task, which is taken from the task column in the row we are working with  -->
	<%= f.label :task %>
	<!-- Sets the text_field to the task column.  -->
	<%= f.text_field :task %>
	<!--  -->
	<%= f.submit %>
<%end%>

app/views/tasks/edit.html.erb
<h1>Edit<h1>

<!-- Here, we pull in the partial, _form.html.erb, which is reusable code.	 -->
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<!-- This is a partial that we pull in from _form.html.erb -->
<%= render 'form'%>
	

<ul>
	<!-- The percents indicate ruby script. Also, since this is a task view, we have access to the Task variables. -->
	<% for task in @tasks %>
		<li id="task_<%= task.id %>">
			<!-- The equal sign indicates that the the Html elements will get what is returned.  -->
			<%= task.task %>
			<!-- Creates link as 'Edit' that re-routes based on the action -->
			||<%= link_to 'Edit',  edit_task_path(task), :id =>"Edit" %>
			<%= link_to 'Delete',  task, :method =>"delete" %>
		</li>
	<% end %>
</ul>